ignore_merge_commits = true
branch_whitelist = ["main", "master"]
tag_prefix = "v"
disable_bump_commit = true
disable_changelog = true

pre_bump_hooks = [
    "uv version {{version}}",
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file "$1"
"""
